// ENUM GLOBAL DA APLICAÇÃO, ELA SERÁ RESPONSÁVEL PELO FORNECIMENTO DE ESTADOS DA APLICAÇÃO PARA AUXILIAR O PROVIDER

enum ViewState {
  idle,        // REPRESENTA O ESTADO INICIAL, O PROVIDER FOI CRIADO, PORÉM AINDA NÃO FOI DISPARADO
  loading,     // REPRESENTA O ESTADO DE CARREGAMENTO, O PROVIDER ESTÁ PROCESSANDO OS DADOS
  success,     // REPRESENTA ESTADO DE SUCESSO, O PROVIDER MANIPULOU O DADOS COM SUCESSO
  error,       // REPRESENTA O ESTADO DE ERRO, HOUVE UM PROBLEMA PARA O PROVIDER MANIPULAR OS DADOS
  empty,       // REPRESENTA O ESTADO DE VAZIO, HOUVE SUCESSO NO PROCESSAMENTO DE DADOS, PORÉM NÃO POSSUI INFORMAÇÕES
}